[tool.black]
line-length = 79
target-version = ['py37']

[tool.coverage.report]
show_missing = true
fail_under = 85

[tool.coverage.html]
directory = 'htmlcov'

[tool.coverage.run]
omit = ['tests/*']
